// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_deep.h"

@interface enum_deep : XCTestCase
@property (strong) enum_deep_t *r;
@end

@implementation enum_deep

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [enum_deep_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_deep {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_1)),EnumByLabel(identifier(animal),identifier(cat),typeId(false,ArrayBuffer(enum_deep, container1),false)))*/
    XCTAssertEqualObjects(((enum_deep_t *)_r).pet_1, ([@"cat" KSENUMWithDictionary:container1_enum_deep_t._animal]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_2)),EnumByLabel(identifier(animal),identifier(hare),typeId(false,ArrayBuffer(enum_deep, container1, container2),false)))*/
    XCTAssertEqualObjects(((enum_deep_t *)_r).pet_2, ([@"hare" KSENUMWithDictionary:container2_container1_enum_deep_t._animal]));
}
@end
