// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_n_struct.h"

@interface repeat_n_struct : XCTestCase
@property (strong) KSRepeatNStruct *r;
@end

@implementation repeat_n_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSRepeatNStruct initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_n_struct {
    XCTAssertEqual(((KSRepeatNStruct *)_r).chunks.count, 2);
    XCTAssertEqual(((KSChunk_RepeatNStruct *)((KSRepeatNStruct *)_r).chunks[0]).offset.unsignedIntValue, 16);
    XCTAssertEqual(((KSChunk_RepeatNStruct *)((KSRepeatNStruct *)_r).chunks[0]).len.unsignedIntValue, 8312);
    XCTAssertEqual(((KSChunk_RepeatNStruct *)((KSRepeatNStruct *)_r).chunks[1]).offset.unsignedIntValue, 8328);
    XCTAssertEqual(((KSChunk_RepeatNStruct *)((KSRepeatNStruct *)_r).chunks[1]).len.unsignedIntValue, 15);
}
@end
