// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "str_eos.h"

@interface str_eos : XCTestCase
@property (strong) KSStrEos *r;
@end

@implementation str_eos

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSStrEos structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_str_eos {
    XCTAssertEqualObjects(((KSStrEos *)_r).str, (@"foo|bar|baz@"));
}
@end
