// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "bcd_user_type_le.h"

@interface bcd_user_type_le : XCTestCase
@property (strong) KSBcdUserTypeLe *r;
@end

@implementation bcd_user_type_le

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/bcd_user_type_le.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSBcdUserTypeLe structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_bcd_user_type_le {
    XCTAssertEqual(((KSLtrObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).ltr).as_int.unsignedLongLongValue, 12345678);
    XCTAssertEqualObjects(((KSLtrObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).ltr).as_str, (@"12345678"));
    XCTAssertEqual(((KSRtlObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).rtl).as_int.unsignedLongLongValue, 87654321);
    XCTAssertEqualObjects(((KSRtlObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).rtl).as_str, (@"87654321"));
    XCTAssertEqual(((KSLeadingZeroLtrObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).leading_zero_ltr).as_int.unsignedLongLongValue, 123456);
    XCTAssertEqualObjects(((KSLeadingZeroLtrObj_BcdUserTypeLe *)((KSBcdUserTypeLe *)_r).leading_zero_ltr).as_str, (@"00123456"));
}
@end
