// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_str_else.h"

@interface switch_manual_str_else : XCTestCase
@property (strong) switch_manual_str_else_t *r;
@end

@implementation switch_manual_str_else

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes2.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [switch_manual_str_else_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_str_else {
    XCTAssertEqual(((switch_manual_str_else_t *)_r).opcodes.count, 4);
    XCTAssertEqualObjects(((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[0]).code, (@"S"));
    XCTAssertEqualObjects(((strval_opcode_switch_manual_str_else_t *)((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[0]).body).value, (@"foo"));
    XCTAssertEqualObjects(((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[1]).code, (@"X"));
    XCTAssertEqual(((noneval_opcode_switch_manual_str_else_t *)((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[1]).body).filler.unsignedIntValue, 66);
    XCTAssertEqualObjects(((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[2]).code, (@"Y"));
    XCTAssertEqual(((noneval_opcode_switch_manual_str_else_t *)((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[2]).body).filler.unsignedIntValue, 51966);
    XCTAssertEqualObjects(((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[3]).code, (@"I"));
    XCTAssertEqual(((intval_opcode_switch_manual_str_else_t *)((opcode_switch_manual_str_else_t *)((switch_manual_str_else_t *)_r).opcodes[3]).body).value.unsignedCharValue, 7);
}
@end
