// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "position_to_end.h"

@interface position_to_end : XCTestCase
@property (strong) position_to_end_t *r;
@end

@implementation position_to_end

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_to_end.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [position_to_end_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_position_to_end {
    XCTAssertEqual(((index_obj_position_to_end_t *)((position_to_end_t *)_r).index).foo.unsignedIntValue, 66);
    XCTAssertEqual(((index_obj_position_to_end_t *)((position_to_end_t *)_r).index).bar.unsignedIntValue, 4660);
}
@end
