// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_coerce_bytes.h"

@interface process_coerce_bytes : XCTestCase
@property (strong) process_coerce_bytes_t *r;
@end

@implementation process_coerce_bytes

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_coerce_bytes.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [process_coerce_bytes_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_coerce_bytes {
    XCTAssertEqual(_r.records[0].flag.unsignedCharValue, 0);
    XCTAssertEqualObjects(_r.records[0].buf, [NSData dataWithBytes:"\x41\x41\x41\x41" length:4]);
    XCTAssertEqual(_r.records[1].flag.unsignedCharValue, 1);
    XCTAssertEqualObjects(_r.records[1].buf, [NSData dataWithBytes:"\x42\x42\x42\x42" length:4]);
}
@end
