// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "if_values.h"

@interface if_values : XCTestCase
@property (strong) KSIfValues *r;
@end

@implementation if_values

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSIfValues initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_if_values {
    XCTAssertEqual(((KSCode_IfValues *)((KSIfValues *)_r).codes[0]).opcode.unsignedCharValue, 80);
    XCTAssertEqual(((KSCode_IfValues *)((KSIfValues *)_r).codes[0]).half_opcode.unsignedLongLongValue, 40);
    XCTAssertEqual(((KSCode_IfValues *)((KSIfValues *)_r).codes[1]).opcode.unsignedCharValue, 65);
    XCTAssertNil(((KSIfValues *)_r).codes[1].half_opcode);
    XCTAssertEqual(((KSCode_IfValues *)((KSIfValues *)_r).codes[2]).opcode.unsignedCharValue, 67);
    XCTAssertNil(((KSIfValues *)_r).codes[2].half_opcode);
}
@end
