// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_n_struct.h"

@interface repeat_n_struct : XCTestCase
@property (strong) repeat_n_struct_t *r;
@end

@implementation repeat_n_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_n_struct_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_n_struct {
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(chunks)),identifier(size)),IntNum(2))*/
    XCTAssertEqual(((repeat_n_struct_t *)_r).chunks.count, 2);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(chunks)),IntNum(0)),identifier(offset)),IntNum(16))*/
    XCTAssertEqual(((chunk_repeat_n_struct_t *)((repeat_n_struct_t *)_r).chunks[0]).offset.unsignedIntValue, 16);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(chunks)),IntNum(0)),identifier(len)),IntNum(8312))*/
    XCTAssertEqual(((chunk_repeat_n_struct_t *)((repeat_n_struct_t *)_r).chunks[0]).len.unsignedIntValue, 8312);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(chunks)),IntNum(1)),identifier(offset)),IntNum(8328))*/
    XCTAssertEqual(((chunk_repeat_n_struct_t *)((repeat_n_struct_t *)_r).chunks[1]).offset.unsignedIntValue, 8328);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(chunks)),IntNum(1)),identifier(len)),IntNum(15))*/
    XCTAssertEqual(((chunk_repeat_n_struct_t *)((repeat_n_struct_t *)_r).chunks[1]).len.unsignedIntValue, 15);
}
@end
