// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nested_types.h"

@interface nested_types : XCTestCase
@property (strong) nested_types_t *r;
@end

@implementation nested_types

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [nested_types_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nested_types {
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(one)),identifier(typed_at_root)),identifier(value_b)),IntNum(80))*/
    XCTAssertEqual(((subtype_b_nested_types_t *)((subtype_a_nested_types_t *)((nested_types_t *)_r).one).typed_at_root).value_b.charValue, 80);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(one)),identifier(typed_here)),identifier(value_c)),IntNum(65))*/
    XCTAssertEqual(((subtype_c_subtype_a_nested_types_t *)((subtype_a_nested_types_t *)((nested_types_t *)_r).one).typed_here).value_c.charValue, 65);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(two)),identifier(value_b)),IntNum(67))*/
    XCTAssertEqual(((subtype_b_nested_types_t *)((nested_types_t *)_r).two).value_b.charValue, 67);
}
@end
