// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_pass_usertype.h"

@interface params_pass_usertype : XCTestCase
@property (strong) params_pass_usertype_t *r;
@end

@implementation params_pass_usertype

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_in_seq.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [params_pass_usertype_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_pass_usertype {
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(first)),identifier(foo)),IntNum(1))*/
    XCTAssertEqual(((block_params_pass_usertype_t *)((params_pass_usertype_t *)_r).first).foo.unsignedCharValue, 1);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(one)),identifier(buf)),List(ArrayBuffer(IntNum(2))))*/
    XCTAssertEqualObjects(((param_type_params_pass_usertype_t *)((params_pass_usertype_t *)_r).one).buf, ([NSData dataWithBytes:"\x02" length:1]));
}
@end
