// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_vs_value_inst.h"

@interface nav_parent_vs_value_inst : XCTestCase
@property (strong) KSNavParentVsValueInst *r;
@end

@implementation nav_parent_vs_value_inst

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNavParentVsValueInst structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_vs_value_inst {
    XCTAssertEqualObjects(((KSNavParentVsValueInst *)_r).s1, (@"foo"));
}
@end
