// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_to_i.h"

@interface enum_to_i : XCTestCase
@property (strong) enum_to_i_t *r;
@end

@implementation enum_to_i

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [enum_to_i_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_to_i {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_1)),EnumByLabel(identifier(animal),identifier(cat),typeId(false,ArrayBuffer(enum_to_i),false)))*/
    XCTAssertEqualObjects(((enum_to_i_t *)_r).pet_1, ([@"cat" KSENUMWithDictionary:enum_to_i_t._animal]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_2)),EnumByLabel(identifier(animal),identifier(chicken),typeId(false,ArrayBuffer(enum_to_i),false)))*/
    XCTAssertEqualObjects(((enum_to_i_t *)_r).pet_2, ([@"chicken" KSENUMWithDictionary:enum_to_i_t._animal]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_1_i)),IntNum(7))*/
    XCTAssertEqual(((enum_to_i_t *)_r).pet_1_i.unsignedLongLongValue, 7);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(pet_1_mod)),IntNum(32775))*/
    XCTAssertEqual(((enum_to_i_t *)_r).pet_1_mod.unsignedLongLongValue, 32775);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(one_lt_two)),Bool(true))*/
    XCTAssertEqual(((enum_to_i_t *)_r).one_lt_two.boolValue, YES);
}
@end
