// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_str.h"

@interface switch_manual_str : XCTestCase
@property (strong) switch_manual_str_t *r;
@end

@implementation switch_manual_str

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [switch_manual_str_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_str {
    XCTAssertEqual(((switch_manual_str_t *)_r).opcodes.count, 4);
    XCTAssertEqualObjects(((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[0]).code, (@"S"));
    XCTAssertEqualObjects(((strval_opcode_switch_manual_str_t *)((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[0]).body).value, (@"foobar"));
    XCTAssertEqualObjects(((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[1]).code, (@"I"));
    XCTAssertEqual(((intval_opcode_switch_manual_str_t *)((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[1]).body).value.unsignedCharValue, 66);
    XCTAssertEqualObjects(((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[2]).code, (@"I"));
    XCTAssertEqual(((intval_opcode_switch_manual_str_t *)((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[2]).body).value.unsignedCharValue, 55);
    XCTAssertEqualObjects(((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[3]).code, (@"S"));
    XCTAssertEqualObjects(((strval_opcode_switch_manual_str_t *)((opcode_switch_manual_str_t *)((switch_manual_str_t *)_r).opcodes[3]).body).value, (@""));
}
@end
