// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nested_same_name.h"

@interface nested_same_name : XCTestCase
@property (strong) KSNestedSameName *r;
@end

@implementation nested_same_name

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNestedSameName structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nested_same_name {
    XCTAssertEqual(((KSMain_NestedSameName *)((KSNestedSameName *)_r).main_data).main_size.intValue, 2);
    XCTAssertEqualObjects(((KSFooObj_Main_NestedSameName *)((KSMain_NestedSameName *)((KSNestedSameName *)_r).main_data).foo).data, ([NSData dataWithBytes:"\x10\x00\x00\x00" length:4]));
}
@end
