// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_n_strz.h"

@interface repeat_n_strz : XCTestCase
@property (strong) repeat_n_strz_t *r;
@end

@implementation repeat_n_strz

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_strz.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_n_strz_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_n_strz {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(qty)),IntNum(2))*/
    XCTAssertEqual(((repeat_n_strz_t *)_r).qty.unsignedIntValue, 2);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(lines)),List(ArrayBuffer(Str(foo), Str(bar))))*/
    XCTAssertEqualObjects(((repeat_n_strz_t *)_r).lines, (@[@"foo", @"bar"]));
}
@end
