// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_xor_const.h"

@interface process_xor_const : XCTestCase
@property (strong) process_xor_const_t *r;
@end

@implementation process_xor_const

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_xor_1.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [process_xor_const_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_xor_const {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(key)),IntNum(255))*/
    XCTAssertEqual(((process_xor_const_t *)_r).key.unsignedCharValue, 255);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(buf)),List(ArrayBuffer(IntNum(102), IntNum(111), IntNum(111), IntNum(32), IntNum(98), IntNum(97), IntNum(114))))*/
    XCTAssertEqualObjects(((process_xor_const_t *)_r).buf, ([NSData dataWithBytes:"\x66\x6F\x6F\x20\x62\x61\x72" length:7]));
}
@end
