// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "buffered_struct.h"

@interface buffered_struct : XCTestCase
@property (strong) KSBufferedStruct *r;
@end

@implementation buffered_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/buffered_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSBufferedStruct structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_buffered_struct {
    XCTAssertEqual(((KSBufferedStruct *)_r).len1.unsignedIntValue, 16);
    XCTAssertEqual(((KSBlock_BufferedStruct *)((KSBufferedStruct *)_r).block1).number1.unsignedIntValue, 66);
    XCTAssertEqual(((KSBlock_BufferedStruct *)((KSBufferedStruct *)_r).block1).number2.unsignedIntValue, 67);
    XCTAssertEqual(((KSBufferedStruct *)_r).len2.unsignedIntValue, 8);
    XCTAssertEqual(((KSBlock_BufferedStruct *)((KSBufferedStruct *)_r).block2).number1.unsignedIntValue, 68);
    XCTAssertEqual(((KSBlock_BufferedStruct *)((KSBufferedStruct *)_r).block2).number2.unsignedIntValue, 69);
    XCTAssertEqual(((KSBufferedStruct *)_r).finisher.unsignedIntValue, 238);
}
@end
