// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_switch.h"

@interface nav_parent_switch : XCTestCase
@property (strong) nav_parent_switch_t *r;
@end

@implementation nav_parent_switch

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav_parent_switch.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [nav_parent_switch_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_switch {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(category)),IntNum(1))*/
    XCTAssertEqual(((nav_parent_switch_t *)_r).category.unsignedCharValue, 1);
    /* simpleAssert: TestAssert(Attribute(CastToType(Attribute(Name(identifier(q1w2e3)),identifier(content)),typeId(false,ArrayBuffer(nav_parent_switch, element_1),false)),identifier(foo)),IntNum(66))*/
    XCTAssertEqual(((element_1_nav_parent_switch_t *)((nav_parent_switch_t *)_r).content).foo.unsignedCharValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(CastToType(Attribute(Name(identifier(q1w2e3)),identifier(content)),typeId(false,ArrayBuffer(nav_parent_switch, element_1),false)),identifier(subelement)),identifier(bar)),IntNum(255))*/
    XCTAssertEqual(((subelement_1_nav_parent_switch_t *)((element_1_nav_parent_switch_t *)((nav_parent_switch_t *)_r).content).subelement).bar.unsignedCharValue, 255);
}
@end
