// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "non_standard.h"

@interface non_standard : XCTestCase
@property (strong) KSNonStandard *r;
@end

@implementation non_standard

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNonStandard initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_non_standard {
    XCTAssertEqual(((KSNonStandard *)_r).foo.unsignedCharValue, 80);
}
@end
