// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nested_types.h"

@interface nested_types : XCTestCase
@property (strong) KSNestedTypes *r;
@end

@implementation nested_types

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNestedTypes initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nested_types {
    XCTAssertEqual(((KSSubtypeB_NestedTypes *)((KSSubtypeA_NestedTypes *)((KSNestedTypes *)_r).one).typed_at_root).value_b.charValue, 80);
    XCTAssertEqual(((KSSubtypeC_SubtypeA_NestedTypes *)((KSSubtypeA_NestedTypes *)((KSNestedTypes *)_r).one).typed_here).value_c.charValue, 65);
    XCTAssertEqual(((KSSubtypeB_NestedTypes *)((KSNestedTypes *)_r).two).value_b.charValue, 67);
}
@end
