// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_str_else.h"

@interface switch_manual_str_else : XCTestCase
@property (strong) KSSwitchManualStrElse *r;
@end

@implementation switch_manual_str_else

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes2.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSSwitchManualStrElse initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_str_else {
    XCTAssertEqual(((KSSwitchManualStrElse *)_r).opcodes.count, 4);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[0]).code, (@"S"));
    XCTAssertEqualObjects(((KSStrval_Opcode_SwitchManualStrElse *)((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[0]).body).value, (@"foo"));
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[1]).code, (@"X"));
    XCTAssertEqual(((KSNoneval_Opcode_SwitchManualStrElse *)((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[1]).body).filler.unsignedIntValue, 66);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[2]).code, (@"Y"));
    XCTAssertEqual(((KSNoneval_Opcode_SwitchManualStrElse *)((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[2]).body).filler.unsignedIntValue, 51966);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[3]).code, (@"I"));
    XCTAssertEqual(((KSIntval_Opcode_SwitchManualStrElse *)((KSOpcode_SwitchManualStrElse *)((KSSwitchManualStrElse *)_r).opcodes[3]).body).value.unsignedCharValue, 7);
}
@end
