// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "multiple_use.h"

@interface multiple_use : XCTestCase
@property (strong) multiple_use_t *r;
@end

@implementation multiple_use

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_abs.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [multiple_use_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_multiple_use {
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(t1)),identifier(first_use)),identifier(value)),IntNum(32))*/
    XCTAssertEqual(((multi_multiple_use_t *)((type_1_multiple_use_t *)((multiple_use_t *)_r).t1).first_use).value.intValue, 32);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(t2)),identifier(second_use)),identifier(value)),IntNum(32))*/
    XCTAssertEqual(((multi_multiple_use_t *)((type_2_multiple_use_t *)((multiple_use_t *)_r).t2).second_use).value.intValue, 32);
}
@end
