// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "buffered_struct.h"

@interface buffered_struct : XCTestCase
@property (strong) buffered_struct_t *r;
@end

@implementation buffered_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/buffered_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [buffered_struct_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_buffered_struct {
    XCTAssertEqual(((buffered_struct_t *)_r).len1.unsignedIntValue, 16);
    XCTAssertEqual(((block_buffered_struct_t *)((buffered_struct_t *)_r).block1).number1.unsignedIntValue, 66);
    XCTAssertEqual(((block_buffered_struct_t *)((buffered_struct_t *)_r).block1).number2.unsignedIntValue, 67);
    XCTAssertEqual(((buffered_struct_t *)_r).len2.unsignedIntValue, 8);
    XCTAssertEqual(((block_buffered_struct_t *)((buffered_struct_t *)_r).block2).number1.unsignedIntValue, 68);
    XCTAssertEqual(((block_buffered_struct_t *)((buffered_struct_t *)_r).block2).number2.unsignedIntValue, 69);
    XCTAssertEqual(((buffered_struct_t *)_r).finisher.unsignedIntValue, 238);
}
@end
