// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "bcd_user_type_le.h"

@interface bcd_user_type_le : XCTestCase
@property (strong) bcd_user_type_le_t *r;
@end

@implementation bcd_user_type_le

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/bcd_user_type_le.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [bcd_user_type_le_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_bcd_user_type_le {
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(ltr)),identifier(as_int)),IntNum(12345678))*/
    XCTAssertEqual(((ltr_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).ltr).as_int.unsignedLongLongValue, 12345678);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(ltr)),identifier(as_str)),Str(12345678))*/
    XCTAssertEqualObjects(((ltr_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).ltr).as_str, (@"12345678"));
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(rtl)),identifier(as_int)),IntNum(87654321))*/
    XCTAssertEqual(((rtl_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).rtl).as_int.unsignedLongLongValue, 87654321);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(rtl)),identifier(as_str)),Str(87654321))*/
    XCTAssertEqualObjects(((rtl_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).rtl).as_str, (@"87654321"));
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(leading_zero_ltr)),identifier(as_int)),IntNum(123456))*/
    XCTAssertEqual(((leading_zero_ltr_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).leading_zero_ltr).as_int.unsignedLongLongValue, 123456);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(leading_zero_ltr)),identifier(as_str)),Str(00123456))*/
    XCTAssertEqualObjects(((leading_zero_ltr_obj_bcd_user_type_le_t *)((bcd_user_type_le_t *)_r).leading_zero_ltr).as_str, (@"00123456"));
}
@end
