// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_eos_u4.h"

@interface repeat_eos_u4 : XCTestCase
@property (strong) KSRepeatEosU4 *r;
@end

@implementation repeat_eos_u4

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_eos_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSRepeatEosU4 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_eos_u4 {
    XCTAssertEqualObjects(((KSRepeatEosU4 *)_r).numbers, (@[@(0), @(66), @(66), @(2069)]));
}
@end
