// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "default_endian_mod.h"

@interface default_endian_mod : XCTestCase
@property (strong) KSDefaultEndianMod *r;
@end

@implementation default_endian_mod

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSDefaultEndianMod initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_default_endian_mod {
    XCTAssertEqual(((KSMainObj_DefaultEndianMod *)((KSDefaultEndianMod *)_r).main).one.intValue, 1262698832);
    XCTAssertEqual(((KSSubnest_MainObj_DefaultEndianMod *)((KSMainObj_DefaultEndianMod *)((KSDefaultEndianMod *)_r).main).nest).two.intValue, -52947);
    XCTAssertEqual(((KSSubnestBe_MainObj_DefaultEndianMod *)((KSMainObj_DefaultEndianMod *)((KSDefaultEndianMod *)_r).main).nest_be).two.intValue, 1346454347);
}
@end
