// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_coerce_usertype1.h"

@interface process_coerce_usertype1 : XCTestCase
@property (strong) KSProcessCoerceUsertype1 *r;
@end

@implementation process_coerce_usertype1

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_coerce_bytes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSProcessCoerceUsertype1 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_coerce_usertype1 {
    XCTAssertEqual(((KSRecord_ProcessCoerceUsertype1 *)((KSProcessCoerceUsertype1 *)_r).records[0]).flag.unsignedCharValue, 0);
    XCTAssertEqual(((KSFoo_ProcessCoerceUsertype1 *)((KSRecord_ProcessCoerceUsertype1 *)((KSProcessCoerceUsertype1 *)_r).records[0]).buf).value.unsignedIntValue, 1094795585);
    XCTAssertEqual(((KSRecord_ProcessCoerceUsertype1 *)((KSProcessCoerceUsertype1 *)_r).records[1]).flag.unsignedCharValue, 1);
    XCTAssertEqual(((KSFoo_ProcessCoerceUsertype1 *)((KSRecord_ProcessCoerceUsertype1 *)((KSProcessCoerceUsertype1 *)_r).records[1]).buf).value.unsignedIntValue, 1111638594);
}
@end
