// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_bytearray.h"

@interface switch_bytearray : XCTestCase
@property (strong) switch_bytearray_t *r;
@end

@implementation switch_bytearray

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [switch_bytearray_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_bytearray {
    XCTAssertEqual(((switch_bytearray_t *)_r).opcodes.count, 4);
    XCTAssertEqualObjects(((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[0]).code, ([NSData dataWithBytes:"\x53" length:1]));
    XCTAssertEqualObjects(((strval_opcode_switch_bytearray_t *)((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[0]).body).value, (@"foobar"));
    XCTAssertEqualObjects(((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[1]).code, ([NSData dataWithBytes:"\x49" length:1]));
    XCTAssertEqual(((intval_opcode_switch_bytearray_t *)((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[1]).body).value.unsignedCharValue, 66);
    XCTAssertEqualObjects(((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[2]).code, ([NSData dataWithBytes:"\x49" length:1]));
    XCTAssertEqual(((intval_opcode_switch_bytearray_t *)((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[2]).body).value.unsignedCharValue, 55);
    XCTAssertEqualObjects(((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[3]).code, ([NSData dataWithBytes:"\x53" length:1]));
    XCTAssertEqualObjects(((strval_opcode_switch_bytearray_t *)((opcode_switch_bytearray_t *)((switch_bytearray_t *)_r).opcodes[3]).body).value, (@""));
}
@end
