// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_rotate.h"

@interface process_rotate : XCTestCase
@property (strong) process_rotate_t *r;
@end

@implementation process_rotate

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_rotate.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [process_rotate_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_rotate {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(buf1)),List(ArrayBuffer(IntNum(72), IntNum(101), IntNum(108), IntNum(108), IntNum(111))))*/
    XCTAssertEqualObjects(((process_rotate_t *)_r).buf1, ([NSData dataWithBytes:"\x48\x65\x6C\x6C\x6F" length:5]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(buf2)),List(ArrayBuffer(IntNum(87), IntNum(111), IntNum(114), IntNum(108), IntNum(100))))*/
    XCTAssertEqualObjects(((process_rotate_t *)_r).buf2, ([NSData dataWithBytes:"\x57\x6F\x72\x6C\x64" length:5]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(buf3)),List(ArrayBuffer(IntNum(84), IntNum(104), IntNum(101), IntNum(114), IntNum(101))))*/
    XCTAssertEqualObjects(((process_rotate_t *)_r).buf3, ([NSData dataWithBytes:"\x54\x68\x65\x72\x65" length:5]));
}
@end
