// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_str.h"

@interface switch_manual_str : XCTestCase
@property (strong) KSSwitchManualStr *r;
@end

@implementation switch_manual_str

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSSwitchManualStr structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_str {
    XCTAssertEqual(((KSSwitchManualStr *)_r).opcodes.count, 4);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[0]).code, (@"S"));
    XCTAssertEqualObjects(((KSStrval_Opcode_SwitchManualStr *)((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[0]).body).value, (@"foobar"));
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[1]).code, (@"I"));
    XCTAssertEqual(((KSIntval_Opcode_SwitchManualStr *)((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[1]).body).value.unsignedCharValue, 66);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[2]).code, (@"I"));
    XCTAssertEqual(((KSIntval_Opcode_SwitchManualStr *)((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[2]).body).value.unsignedCharValue, 55);
    XCTAssertEqualObjects(((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[3]).code, (@"S"));
    XCTAssertEqualObjects(((KSStrval_Opcode_SwitchManualStr *)((KSOpcode_SwitchManualStr *)((KSSwitchManualStr *)_r).opcodes[3]).body).value, (@""));
}
@end
