// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_io_pos.h"

@interface expr_io_pos : XCTestCase
@property (strong) KSExprIoPos *r;
@end

@implementation expr_io_pos

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/expr_io_pos.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExprIoPos structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_io_pos {
    XCTAssertEqualObjects(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream1).my_str, (@"CURIOSITY"));
    XCTAssertEqualObjects(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream1).body, ([NSData dataWithBytes:"\x11\x22\x33\x44" length:4]));
    XCTAssertEqual(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream1).number.unsignedShortValue, 66);
    XCTAssertEqualObjects(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream2).my_str, (@"KILLED"));
    XCTAssertEqualObjects(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream2).body, ([NSData dataWithBytes:"\x61\x20\x63\x61\x74" length:5]));
    XCTAssertEqual(((KSAllPlusNumber_ExprIoPos *)((KSExprIoPos *)_r).substream2).number.unsignedShortValue, 103);
}
@end
