// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "multiple_use.h"

@interface multiple_use : XCTestCase
@property (strong) KSMultipleUse *r;
@end

@implementation multiple_use

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_abs.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSMultipleUse structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_multiple_use {
    XCTAssertEqual(((KSMulti_MultipleUse *)((KSType1_MultipleUse *)((KSMultipleUse *)_r).t1).first_use).value.intValue, 32);
    XCTAssertEqual(((KSMulti_MultipleUse *)((KSType2_MultipleUse *)((KSMultipleUse *)_r).t2).second_use).value.intValue, 32);
}
@end
