// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_false.h"

@interface nav_parent_false : XCTestCase
@property (strong) KSNavParentFalse *r;
@end

@implementation nav_parent_false

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav_parent_codes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNavParentFalse structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_false {
    XCTAssertEqual(((KSNavParentFalse *)_r).child_size.unsignedCharValue, 3);
    XCTAssertEqual(((KSChild_NavParentFalse *)((KSParentA_NavParentFalse *)((KSNavParentFalse *)_r).element_a).foo).code.unsignedCharValue, 73);
    XCTAssertEqualObjects(((KSChild_NavParentFalse *)((KSParentA_NavParentFalse *)((KSNavParentFalse *)_r).element_a).foo).more, ([NSData dataWithBytes:"\x31\x32\x33" length:3]));
    XCTAssertEqual(((KSChild_NavParentFalse *)((KSParentB_NavParentFalse *)((KSParentA_NavParentFalse *)((KSNavParentFalse *)_r).element_a).bar).foo).code.unsignedCharValue, 66);
    XCTAssertEqual(((KSChild_NavParentFalse *)((KSParentB_NavParentFalse *)((KSNavParentFalse *)_r).element_b).foo).code.unsignedCharValue, 98);
}
@end
