// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_2.h"

@interface expr_2 : XCTestCase
@property (strong) KSExpr2 *r;
@end

@implementation expr_2

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/str_encodings.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExpr2 structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_2 {
    XCTAssertEqual(((KSModStr_Expr2 *)((KSExpr2 *)_r).str1).len_orig.unsignedShortValue, 10);
    XCTAssertEqual(((KSModStr_Expr2 *)((KSExpr2 *)_r).str1).len_mod.unsignedLongLongValue, 7);
    XCTAssertEqualObjects(((KSModStr_Expr2 *)((KSExpr2 *)_r).str1).str, (@"Some AS"));
    XCTAssertEqual(((KSExpr2 *)_r).str1_len.unsignedLongLongValue, 7);
    XCTAssertEqual(((KSExpr2 *)_r).str1_len_mod.unsignedLongLongValue, 7);
    XCTAssertEqual(((KSExpr2 *)_r).str1_byte1.unsignedCharValue, 73);
    XCTAssertEqual(((KSExpr2 *)_r).str1_avg.unsignedLongLongValue, 73);
    XCTAssertEqualObjects(((KSExpr2 *)_r).str1_char5, (@"e"));
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str1_tuple5).byte0.unsignedCharValue, 101);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str1_tuple5).byte0.unsignedCharValue, 101);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str1_tuple5).byte1.unsignedCharValue, 32);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str1_tuple5).byte2.unsignedCharValue, 65);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str1_tuple5).avg.unsignedLongLongValue, 48);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str2_tuple5).byte0.unsignedCharValue, 101);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str2_tuple5).byte1.unsignedCharValue, 32);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str2_tuple5).byte2.unsignedCharValue, 65);
    XCTAssertEqual(((KSTuple_Expr2 *)((KSExpr2 *)_r).str2_tuple5).avg.unsignedLongLongValue, 48);
}
@end
