// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_eos_bit.h"

@interface repeat_eos_bit : XCTestCase
@property (strong) repeat_eos_bit_t *r;
@end

@implementation repeat_eos_bit

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_eos_bit_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_eos_bit {
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(nibbles)),identifier(size)),IntNum(16))*/
    XCTAssertEqual(((repeat_eos_bit_t *)_r).nibbles.count, 16);
}
@end
