// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "str_pad_term_empty.h"

@interface str_pad_term_empty : XCTestCase
@property (strong) str_pad_term_empty_t *r;
@end

@implementation str_pad_term_empty

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/str_pad_term_empty.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [str_pad_term_empty_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_str_pad_term_empty {
    XCTAssertEqualObjects(((str_pad_term_empty_t *)_r).str_pad, (@""));
    XCTAssertEqualObjects(((str_pad_term_empty_t *)_r).str_term, (@""));
    XCTAssertEqualObjects(((str_pad_term_empty_t *)_r).str_term_and_pad, (@""));
    XCTAssertEqualObjects(((str_pad_term_empty_t *)_r).str_term_include, (@"@"));
}
@end
