// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_call_short.h"

@interface params_call_short : XCTestCase
@property (strong) KSParamsCallShort *r;
@end

@implementation params_call_short

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSParamsCallShort initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_call_short {
    XCTAssertEqualObjects(((KSMyStr1_ParamsCallShort *)((KSParamsCallShort *)_r).buf1).body, (@"foo|b"));
    XCTAssertEqualObjects(((KSMyStr2_ParamsCallShort *)((KSParamsCallShort *)_r).buf2).body, (@"ar|ba"));
    XCTAssertEqual(((KSMyStr2_ParamsCallShort *)((KSParamsCallShort *)_r).buf2).trailer.unsignedCharValue, 122);
}
@end
