// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_sizeof_type_0.h"

@interface expr_sizeof_type_0 : XCTestCase
@property (strong) KSExprSizeofType0 *r;
@end

@implementation expr_sizeof_type_0

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExprSizeofType0 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_sizeof_type_0 {
    XCTAssertEqual(((KSExprSizeofType0 *)_r).sizeof_block.unsignedLongLongValue, ((1 + 4) + 2));
}
@end
