// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "index_sizes.h"

@interface index_sizes : XCTestCase
@property (strong) KSIndexSizes *r;
@end

@implementation index_sizes

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/index_sizes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSIndexSizes initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_index_sizes {
    XCTAssertEqual(((KSIndexSizes *)_r).qty.unsignedIntValue, 3);
    XCTAssertEqual(((KSIndexSizes *)_r).sizes[0].unsignedIntValue, 1);
    XCTAssertEqual(((KSIndexSizes *)_r).sizes[1].unsignedIntValue, 8);
    XCTAssertEqual(((KSIndexSizes *)_r).sizes[2].unsignedIntValue, 4);
    XCTAssertEqualObjects(((KSIndexSizes *)_r).bufs[0], (@"A"));
    XCTAssertEqualObjects(((KSIndexSizes *)_r).bufs[1], (@"BBBBBBBB"));
    XCTAssertEqualObjects(((KSIndexSizes *)_r).bufs[2], (@"CCCC"));
}
@end
