// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "instance_std_array.h"

@interface instance_std_array : XCTestCase
@property (strong) KSInstanceStdArray *r;
@end

@implementation instance_std_array

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/instance_std_array.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSInstanceStdArray structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_instance_std_array {
    XCTAssertEqual(((KSInstanceStdArray *)_r).ofs.unsignedIntValue, 16);
    XCTAssertEqual(((KSInstanceStdArray *)_r).qty_entries.unsignedIntValue, 3);
    XCTAssertEqual(((KSInstanceStdArray *)_r).entry_size.unsignedIntValue, 4);
    XCTAssertEqual(((KSInstanceStdArray *)_r).entries.count, 3);
    XCTAssertEqualObjects(((KSInstanceStdArray *)_r).entries[0], ([NSData dataWithBytes:"\x11\x11\x11\x11" length:4]));
    XCTAssertEqualObjects(((KSInstanceStdArray *)_r).entries[1], ([NSData dataWithBytes:"\x22\x22\x22\x22" length:4]));
    XCTAssertEqualObjects(((KSInstanceStdArray *)_r).entries[2], ([NSData dataWithBytes:"\x33\x33\x33\x33" length:4]));
}
@end
