// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "bcd_user_type_be.h"

@interface bcd_user_type_be : XCTestCase
@property (strong) KSBcdUserTypeBe *r;
@end

@implementation bcd_user_type_be

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/bcd_user_type_be.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSBcdUserTypeBe initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_bcd_user_type_be {
    XCTAssertEqual(((KSLtrObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).ltr).as_int.unsignedLongLongValue, 12345678);
    XCTAssertEqualObjects(((KSLtrObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).ltr).as_str, (@"12345678"));
    XCTAssertEqual(((KSRtlObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).rtl).as_int.unsignedLongLongValue, 87654321);
    XCTAssertEqualObjects(((KSRtlObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).rtl).as_str, (@"87654321"));
    XCTAssertEqual(((KSLeadingZeroLtrObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).leading_zero_ltr).as_int.unsignedLongLongValue, 123456);
    XCTAssertEqualObjects(((KSLeadingZeroLtrObj_BcdUserTypeBe *)((KSBcdUserTypeBe *)_r).leading_zero_ltr).as_str, (@"00123456"));
}
@end
