// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "non_standard.h"

@interface non_standard : XCTestCase
@property (strong) non_standard_t *r;
@end

@implementation non_standard

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [non_standard_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_non_standard {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(foo)),IntNum(80))*/
    XCTAssertEqual(((non_standard_t *)_r).foo.unsignedCharValue, 80);
}
@end
