// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_switch.h"

@interface nav_parent_switch : XCTestCase
@property (strong) KSNavParentSwitch *r;
@end

@implementation nav_parent_switch

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav_parent_switch.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNavParentSwitch initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_switch {
    XCTAssertEqual(((KSNavParentSwitch *)_r).category.unsignedCharValue, 1);
    XCTAssertEqual(((KSElement1_NavParentSwitch *)((KSNavParentSwitch *)_r).content).foo.unsignedCharValue, 66);
    XCTAssertEqual(((KSSubelement1_NavParentSwitch *)((KSElement1_NavParentSwitch *)((KSNavParentSwitch *)_r).content).subelement).bar.unsignedCharValue, 255);
}
@end
