// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_int_else.h"

@interface switch_manual_int_else : XCTestCase
@property (strong) switch_manual_int_else_t *r;
@end

@implementation switch_manual_int_else

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_opcodes2.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [switch_manual_int_else_t initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_int_else {
    XCTAssertEqual(((switch_manual_int_else_t *)_r).opcodes.count, 4);
    XCTAssertEqual(((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[0]).code.unsignedCharValue, 83);
    XCTAssertEqualObjects(((strval_opcode_switch_manual_int_else_t *)((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[0]).body).value, (@"foo"));
    XCTAssertEqual(((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[1]).code.unsignedCharValue, 88);
    XCTAssertEqual(((noneval_opcode_switch_manual_int_else_t *)((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[1]).body).filler.unsignedIntValue, 66);
    XCTAssertEqual(((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[2]).code.unsignedCharValue, 89);
    XCTAssertEqual(((noneval_opcode_switch_manual_int_else_t *)((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[2]).body).filler.unsignedIntValue, 51966);
    XCTAssertEqual(((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[3]).code.unsignedCharValue, 73);
    XCTAssertEqual(((intval_opcode_switch_manual_int_else_t *)((opcode_switch_manual_int_else_t *)((switch_manual_int_else_t *)_r).opcodes[3]).body).value.unsignedCharValue, 7);
}
@end
