// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_eos_struct.h"

@interface repeat_eos_struct : XCTestCase
@property (strong) repeat_eos_struct_t *r;
@end

@implementation repeat_eos_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_eos_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_eos_struct_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_eos_struct {
    XCTAssertEqual(((repeat_eos_struct_t *)_r).chunks.count, 2);
    XCTAssertEqual(((chunk_repeat_eos_struct_t *)((repeat_eos_struct_t *)_r).chunks[0]).offset.unsignedIntValue, 0);
    XCTAssertEqual(((chunk_repeat_eos_struct_t *)((repeat_eos_struct_t *)_r).chunks[0]).len.unsignedIntValue, 66);
    XCTAssertEqual(((chunk_repeat_eos_struct_t *)((repeat_eos_struct_t *)_r).chunks[1]).offset.unsignedIntValue, 66);
    XCTAssertEqual(((chunk_repeat_eos_struct_t *)((repeat_eos_struct_t *)_r).chunks[1]).len.unsignedIntValue, 2069);
}
@end
