// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "position_in_seq.h"

@interface position_in_seq : XCTestCase
@property (strong) position_in_seq_t *r;
@end

@implementation position_in_seq

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_in_seq.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [position_in_seq_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_position_in_seq {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(numbers)),List(ArrayBuffer(BinOp(IntNum(0),Add,IntNum(1)), IntNum(2), IntNum(3))))*/
    XCTAssertEqualObjects(((position_in_seq_t *)_r).numbers, (@[@((0 + 1)), @(2), @(3)]));
}
@end
