// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_sizeof_type_1.h"

@interface expr_sizeof_type_1 : XCTestCase
@property (strong) KSExprSizeofType1 *r;
@end

@implementation expr_sizeof_type_1

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExprSizeofType1 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_sizeof_type_1 {
    XCTAssertEqual(((KSExprSizeofType1 *)_r).sizeof_block.unsignedLongLongValue, (((1 + 4) + 2) + 4));
    XCTAssertEqual(((KSExprSizeofType1 *)_r).sizeof_subblock.unsignedLongLongValue, 4);
}
@end
