// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_1.h"

@interface expr_1 : XCTestCase
@property (strong) KSExpr1 *r;
@end

@implementation expr_1

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/str_encodings.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExpr1 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_1 {
    XCTAssertEqual(((KSExpr1 *)_r).len_of_1.unsignedShortValue, 10);
    XCTAssertEqual(((KSExpr1 *)_r).len_of_1_mod.unsignedLongLongValue, 8);
    XCTAssertEqualObjects(((KSExpr1 *)_r).str1, (@"Some ASC"));
    XCTAssertEqual(((KSExpr1 *)_r).str1_len.unsignedLongLongValue, 8);
}
@end
