// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "user_type.h"

@interface user_type : XCTestCase
@property (strong) user_type_t *r;
@end

@implementation user_type

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_until_s4.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [user_type_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_user_type {
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(one)),identifier(width)),IntNum(66))*/
    XCTAssertEqual(((header_user_type_t *)((user_type_t *)_r).one).width.unsignedIntValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(one)),identifier(height)),IntNum(4919))*/
    XCTAssertEqual(((header_user_type_t *)((user_type_t *)_r).one).height.unsignedIntValue, 4919);
}
@end
