// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "fixed_struct.h"

@interface fixed_struct : XCTestCase
@property (strong) fixed_struct_t *r;
@end

@implementation fixed_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [fixed_struct_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_fixed_struct {
    XCTAssertEqual(_r.hdr.uint8.unsignedCharValue, 255);
    XCTAssertEqual(_r.hdr.uint16.unsignedShortValue, 65535);
    XCTAssertEqual(_r.hdr.uint32.unsignedIntValue, 4294967295UL);
    XCTAssertEqual(_r.hdr.uint64.unsignedLongLongValue, 18446744073709551615ULL);
    XCTAssertEqual(_r.hdr.sint8.charValue, -1);
    XCTAssertEqual(_r.hdr.sint16.shortValue, -1);
    XCTAssertEqual(_r.hdr.sint32.intValue, -1);
    XCTAssertEqual(_r.hdr.sint64.longLongValue, -1);
    XCTAssertEqual(_r.hdr.uint16le.unsignedShortValue, 66);
    XCTAssertEqual(_r.hdr.uint32le.unsignedIntValue, 66);
    XCTAssertEqual(_r.hdr.uint64le.unsignedLongLongValue, 66);
    XCTAssertEqual(_r.hdr.sint16le.shortValue, -66);
    XCTAssertEqual(_r.hdr.sint32le.intValue, -66);
    XCTAssertEqual(_r.hdr.sint64le.longLongValue, -66);
    XCTAssertEqual(_r.hdr.uint16be.unsignedShortValue, 66);
    XCTAssertEqual(_r.hdr.uint32be.unsignedIntValue, 66);
    XCTAssertEqual(_r.hdr.uint64be.unsignedLongLongValue, 66);
    XCTAssertEqual(_r.hdr.sint16be.shortValue, -66);
    XCTAssertEqual(_r.hdr.sint32be.intValue, -66);
    XCTAssertEqual(_r.hdr.sint64be.longLongValue, -66);
}
@end
