// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_enum.h"

@interface params_enum : XCTestCase
@property (strong) KSParamsEnum *r;
@end

@implementation params_enum

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSParamsEnum initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_enum {
    XCTAssertEqualObjects(((KSParamsEnum *)_r).one, ([@"cat" KSENUMWithDictionary:KSParamsEnum._animal]));
    XCTAssertEqual(((KSWithParam_ParamsEnum *)((KSParamsEnum *)_r).invoke_with_param).is_cat.boolValue, YES);
}
@end
