// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_3.h"

@interface expr_3 : XCTestCase
@property (strong) KSExpr3 *r;
@end

@implementation expr_3

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExpr3 initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_3 {
    XCTAssertEqual(((KSExpr3 *)_r).one.unsignedCharValue, 80);
    XCTAssertEqualObjects(((KSExpr3 *)_r).two, (@"ACK"));
    XCTAssertEqualObjects(((KSExpr3 *)_r).three, (@"@ACK"));
    XCTAssertEqualObjects(((KSExpr3 *)_r).four, (@"_ACK_"));
    XCTAssertEqual(((KSExpr3 *)_r).is_str_eq.boolValue, YES);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_ne.boolValue, NO);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_lt.boolValue, YES);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_gt.boolValue, NO);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_le.boolValue, YES);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_ge.boolValue, NO);
    XCTAssertEqual(((KSExpr3 *)_r).is_str_lt2.boolValue, YES);
    XCTAssertEqual(((KSExpr3 *)_r).test_not.boolValue, YES);
}
@end
