// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_to_user.h"

@interface process_to_user : XCTestCase
@property (strong) KSProcessToUser *r;
@end

@implementation process_to_user

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_rotate.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSProcessToUser initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_to_user {
    XCTAssertEqualObjects(((KSJustStr_ProcessToUser *)((KSProcessToUser *)_r).buf1).str, (@"Hello"));
}
@end
