// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_pass_usertype.h"

@interface params_pass_usertype : XCTestCase
@property (strong) params_pass_usertype_t *r;
@end

@implementation params_pass_usertype

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_in_seq.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [params_pass_usertype_t initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_pass_usertype {
    XCTAssertEqual(((block_params_pass_usertype_t *)((params_pass_usertype_t *)_r).first).foo.unsignedCharValue, 1);
    XCTAssertEqualObjects(((param_type_params_pass_usertype_t *)((params_pass_usertype_t *)_r).one).buf, ([NSData dataWithBytes:"\x02" length:1]));
}
@end
