// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_enum.h"

@interface params_enum : XCTestCase
@property (strong) params_enum_t *r;
@end

@implementation params_enum

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [params_enum_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_enum {
    XCTAssertEqualObjects(((params_enum_t *)_r).one, ([@"cat" KSENUMWithDictionary:params_enum_t._animal]));
    XCTAssertEqual(((with_param_params_enum_t *)((params_enum_t *)_r).invoke_with_param).is_cat.boolValue, YES);
}
@end
