// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_bytes_cmp.h"

@interface expr_bytes_cmp : XCTestCase
@property (strong) KSExprBytesCmp *r;
@end

@implementation expr_bytes_cmp

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExprBytesCmp structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_bytes_cmp {
    XCTAssertEqualObjects(((KSExprBytesCmp *)_r).one, ([NSData dataWithBytes:"\x50" length:1]));
    XCTAssertEqualObjects(((KSExprBytesCmp *)_r).two, ([NSData dataWithBytes:"\x41\x43\x4B" length:3]));
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_eq.boolValue, YES);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_ne.boolValue, NO);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_lt.boolValue, YES);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_gt.boolValue, NO);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_le.boolValue, YES);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_ge.boolValue, NO);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_lt2.boolValue, NO);
    XCTAssertEqual(((KSExprBytesCmp *)_r).is_gt2.boolValue, YES);
}
@end
