// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "hello_world.h"

@interface hello_world : XCTestCase
@property (strong) KSHelloWorld *r;
@end

@implementation hello_world

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSHelloWorld structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_hello_world {
    XCTAssertEqual(((KSHelloWorld *)_r).one.unsignedCharValue, 80);
}
@end
