// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "position_abs.h"

@interface position_abs : XCTestCase
@property (strong) position_abs_t *r;
@end

@implementation position_abs

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_abs.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [position_abs_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_position_abs {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(index_offset)),IntNum(32))*/
    XCTAssertEqual(((position_abs_t *)_r).index_offset.unsignedIntValue, 32);
    /* simpleAssert: TestAssert(Attribute(Attribute(Name(identifier(q1w2e3)),identifier(index)),identifier(entry)),Str(foo))*/
    XCTAssertEqualObjects(((index_obj_position_abs_t *)((position_abs_t *)_r).index).entry, (@"foo"));
}
@end
