// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "cast_to_top.h"

@interface cast_to_top : XCTestCase
@property (strong) KSCastToTop *r;
@end

@implementation cast_to_top

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSCastToTop structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_cast_to_top {
    XCTAssertEqual(((KSCastToTop *)_r).code.unsignedCharValue, 80);
    XCTAssertEqual(((KSCastToTop *)((KSCastToTop *)_r).header).code.unsignedCharValue, 65);
    XCTAssertEqual(((KSCastToTop *)((KSCastToTop *)_r).header_casted).code.unsignedCharValue, 65);
}
@end
