// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "bytes_pad_term.h"

@interface bytes_pad_term : XCTestCase
@property (strong) bytes_pad_term_t *r;
@end

@implementation bytes_pad_term

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/str_pad_term.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [bytes_pad_term_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_bytes_pad_term {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(str_pad)),List(ArrayBuffer(IntNum(115), IntNum(116), IntNum(114), IntNum(49))))*/
    XCTAssertEqualObjects(((bytes_pad_term_t *)_r).str_pad, ([NSData dataWithBytes:"\x73\x74\x72\x31" length:4]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(str_term)),List(ArrayBuffer(IntNum(115), IntNum(116), IntNum(114), IntNum(50), IntNum(102), IntNum(111), IntNum(111))))*/
    XCTAssertEqualObjects(((bytes_pad_term_t *)_r).str_term, ([NSData dataWithBytes:"\x73\x74\x72\x32\x66\x6F\x6F" length:7]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(str_term_and_pad)),List(ArrayBuffer(IntNum(115), IntNum(116), IntNum(114), IntNum(43), IntNum(43), IntNum(43), IntNum(51), IntNum(98), IntNum(97), IntNum(114), IntNum(43), IntNum(43), IntNum(43))))*/
    XCTAssertEqualObjects(((bytes_pad_term_t *)_r).str_term_and_pad, ([NSData dataWithBytes:"\x73\x74\x72\x2B\x2B\x2B\x33\x62\x61\x72\x2B\x2B\x2B" length:13]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(str_term_include)),List(ArrayBuffer(IntNum(115), IntNum(116), IntNum(114), IntNum(52), IntNum(98), IntNum(97), IntNum(122), IntNum(64))))*/
    XCTAssertEqualObjects(((bytes_pad_term_t *)_r).str_term_include, ([NSData dataWithBytes:"\x73\x74\x72\x34\x62\x61\x7A\x40" length:8]));
}
@end
