// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_switch.h"

@interface nav_parent_switch : XCTestCase
@property (strong) nav_parent_switch_t *r;
@end

@implementation nav_parent_switch

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav_parent_switch.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [nav_parent_switch_t initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_switch {
    XCTAssertEqual(((nav_parent_switch_t *)_r).category.unsignedCharValue, 1);
    XCTAssertEqual(((element_1_nav_parent_switch_t *)((nav_parent_switch_t *)_r).content).foo.unsignedCharValue, 66);
    XCTAssertEqual(((subelement_1_nav_parent_switch_t *)((element_1_nav_parent_switch_t *)((nav_parent_switch_t *)_r).content).subelement).bar.unsignedCharValue, 255);
}
@end
