// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_to_user.h"

@interface process_to_user : XCTestCase
@property (strong) process_to_user_t *r;
@end

@implementation process_to_user

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_rotate.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [process_to_user_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_to_user {
    XCTAssertEqualObjects(((just_str_process_to_user_t *)((process_to_user_t *)_r).buf1).str, @"Hello");
}
@end
