// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "if_struct.h"

@interface if_struct : XCTestCase
@property (strong) KSIfStruct *r;
@end

@implementation if_struct

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/if_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSIfStruct initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_if_struct {
    XCTAssertEqual(((KSOperation_IfStruct *)((KSIfStruct *)_r).op1).opcode.unsignedCharValue, 83);
    XCTAssertEqualObjects(((KSArgStr_IfStruct *)((KSOperation_IfStruct *)((KSIfStruct *)_r).op1).arg_str).str, (@"foo"));
    XCTAssertEqual(((KSOperation_IfStruct *)((KSIfStruct *)_r).op2).opcode.unsignedCharValue, 84);
    XCTAssertEqual(((KSArgTuple_IfStruct *)((KSOperation_IfStruct *)((KSIfStruct *)_r).op2).arg_tuple).num1.unsignedCharValue, 66);
    XCTAssertEqual(((KSArgTuple_IfStruct *)((KSOperation_IfStruct *)((KSIfStruct *)_r).op2).arg_tuple).num2.unsignedCharValue, 67);
    XCTAssertEqual(((KSOperation_IfStruct *)((KSIfStruct *)_r).op3).opcode.unsignedCharValue, 83);
    XCTAssertEqualObjects(((KSArgStr_IfStruct *)((KSOperation_IfStruct *)((KSIfStruct *)_r).op3).arg_str).str, (@"bar"));
}
@end
