// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "switch_manual_int_size_else.h"

@interface switch_manual_int_size_else : XCTestCase
@property (strong) switch_manual_int_size_else_t *r;
@end

@implementation switch_manual_int_size_else

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/switch_tlv.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [switch_manual_int_size_else_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_switch_manual_int_size_else {
    XCTAssertEqual(((switch_manual_int_size_else_t *)_r).chunks.count, 4);
    XCTAssertEqual(((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[0]).code.unsignedCharValue, 17);
    XCTAssertEqualObjects(((chunk_meta_chunk_switch_manual_int_size_else_t *)((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[0]).body).title, (@"Stuff"));
    XCTAssertEqualObjects(((chunk_meta_chunk_switch_manual_int_size_else_t *)((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[0]).body).author, (@"Me"));
    XCTAssertEqual(((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[1]).code.unsignedCharValue, 34);
    XCTAssertEqualObjects(((chunk_dir_chunk_switch_manual_int_size_else_t *)((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[1]).body).entries, (@[@"AAAA", @"BBBB", @"CCCC"]));
    XCTAssertEqual(((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[2]).code.unsignedCharValue, 51);
    XCTAssertEqualObjects(((dummy_chunk_switch_manual_int_size_else_t *)((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[2]).body).rest, ([NSData dataWithBytes:"\x10\x20\x30\x40\x50\x60\x70\x80" length:8]));
    XCTAssertEqual(((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[3]).code.unsignedCharValue, 255);
    XCTAssertEqualObjects(((dummy_chunk_switch_manual_int_size_else_t *)((chunk_switch_manual_int_size_else_t *)((switch_manual_int_size_else_t *)_r).chunks[3]).body).rest, ([NSData dataWithBytes:"" length:0]));
}
@end
