// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_coerce_usertype2.h"

@interface process_coerce_usertype2 : XCTestCase
@property (strong) KSProcessCoerceUsertype2 *r;
@end

@implementation process_coerce_usertype2

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_coerce_bytes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSProcessCoerceUsertype2 structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_coerce_usertype2 {
    XCTAssertEqual(((KSRecord_ProcessCoerceUsertype2 *)((KSProcessCoerceUsertype2 *)_r).records[0]).flag.unsignedCharValue, 0);
    XCTAssertEqual(((KSFoo_ProcessCoerceUsertype2 *)((KSRecord_ProcessCoerceUsertype2 *)((KSProcessCoerceUsertype2 *)_r).records[0]).buf).value.unsignedIntValue, 1094795585);
    XCTAssertEqual(((KSRecord_ProcessCoerceUsertype2 *)((KSProcessCoerceUsertype2 *)_r).records[1]).flag.unsignedCharValue, 1);
    XCTAssertEqual(((KSFoo_ProcessCoerceUsertype2 *)((KSRecord_ProcessCoerceUsertype2 *)((KSProcessCoerceUsertype2 *)_r).records[1]).buf).value.unsignedIntValue, 1111638594);
}
@end
