// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "default_endian_expr_is_be.h"

@interface default_endian_expr_is_be : XCTestCase
@property (strong) KSDefaultEndianExprIsBe *r;
@end

@implementation default_endian_expr_is_be

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/endian_expr.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSDefaultEndianExprIsBe initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_default_endian_expr_is_be {
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).indicator, ([NSData dataWithBytes:"\x49\x49" length:2]));
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).main).some_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).main).some_int_be.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).main).some_int_le.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).main).inst_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSSubMainObj_MainObj_Doc_DefaultEndianExprIsBe *)((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[0]).main).inst_sub).foo.unsignedIntValue, 66);
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).indicator, ([NSData dataWithBytes:"\x4D\x4D" length:2]));
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).main).some_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).main).some_int_be.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).main).some_int_le.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).main).inst_int.unsignedIntValue, 1107296256);
    XCTAssertEqual(((KSSubMainObj_MainObj_Doc_DefaultEndianExprIsBe *)((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[1]).main).inst_sub).foo.unsignedIntValue, 1107296256);
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).indicator, ([NSData dataWithBytes:"\x58\x58" length:2]));
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).main).some_int.unsignedIntValue, 1107296256);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).main).some_int_be.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).main).some_int_le.unsignedShortValue, 66);
    XCTAssertEqual(((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).main).inst_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSSubMainObj_MainObj_Doc_DefaultEndianExprIsBe *)((KSMainObj_Doc_DefaultEndianExprIsBe *)((KSDoc_DefaultEndianExprIsBe *)((KSDefaultEndianExprIsBe *)_r).docs[2]).main).inst_sub).foo.unsignedIntValue, 66);
}
@end
