// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_until_s4.h"

@interface repeat_until_s4 : XCTestCase
@property (strong) repeat_until_s4_t *r;
@end

@implementation repeat_until_s4

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_until_s4.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_until_s4_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_until_s4 {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(entries)),List(ArrayBuffer(IntNum(66), IntNum(4919), UnaryOp(Minus,IntNum(251658241)), UnaryOp(Minus,IntNum(1)))))*/
    XCTAssertEqualObjects(((repeat_until_s4_t *)_r).entries, (@[@(66), @(4919), @(-251658241), @(-1)]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(afterall)),Str(foobar))*/
    XCTAssertEqualObjects(((repeat_until_s4_t *)_r).afterall, (@"foobar"));
}
@end
