// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "position_in_seq.h"

@interface position_in_seq : XCTestCase
@property (strong) KSPositionInSeq *r;
@end

@implementation position_in_seq

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/position_in_seq.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSPositionInSeq structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_position_in_seq {
    XCTAssertEqualObjects(((KSPositionInSeq *)_r).numbers, (@[@((0 + 1)), @(2), @(3)]));
}
@end
