// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_n_strz.h"

@interface repeat_n_strz : XCTestCase
@property (strong) KSRepeatNStrz *r;
@end

@implementation repeat_n_strz

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSRepeatNStrz structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_n_strz {
    XCTAssertEqual(((KSRepeatNStrz *)_r).qty.unsignedIntValue, 2);
    XCTAssertEqualObjects(((KSRepeatNStrz *)_r).lines, (@[@"foo", @"bar"]));
}
@end
