// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_negative.h"

@interface enum_negative : XCTestCase
@property (strong) enum_negative_t *r;
@end

@implementation enum_negative

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_negative.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [enum_negative_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_negative {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(f1)),EnumByLabel(identifier(constants),identifier(negative_one),typeId(false,ArrayBuffer(enum_negative),false)))*/
    XCTAssertEqualObjects(((enum_negative_t *)_r).f1, ([@"negative_one" KSENUMWithDictionary:enum_negative_t._constants]));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(f2)),EnumByLabel(identifier(constants),identifier(positive_one),typeId(false,ArrayBuffer(enum_negative),false)))*/
    XCTAssertEqualObjects(((enum_negative_t *)_r).f2, ([@"positive_one" KSENUMWithDictionary:enum_negative_t._constants]));
}
@end
