// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_to_i.h"

@interface enum_to_i : XCTestCase
@property (strong) enum_to_i_t *r;
@end

@implementation enum_to_i

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [enum_to_i_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_to_i {
    XCTAssertEqualObjects(((enum_to_i_t *)_r).pet_1, [@"cat" KSENUMWithDictionary:enum_to_i_t._animal]);
    XCTAssertEqualObjects(((enum_to_i_t *)_r).pet_2, [@"chicken" KSENUMWithDictionary:enum_to_i_t._animal]);
    XCTAssertEqual(((enum_to_i_t *)_r).pet_1_i.unsignedLongLongValue, 7);
    XCTAssertEqual(((enum_to_i_t *)_r).pet_1_mod.unsignedLongLongValue, 32775);
    XCTAssertEqual(((enum_to_i_t *)_r).one_lt_two.boolValue, YES);
}
@end
