// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_3.h"

@interface expr_3 : XCTestCase
@property (strong) expr_3_t *r;
@end

@implementation expr_3

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [expr_3_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_3 {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(one)),IntNum(80))*/
    XCTAssertEqual(((expr_3_t *)_r).one.unsignedCharValue, 80);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(two)),Str(ACK))*/
    XCTAssertEqualObjects(((expr_3_t *)_r).two, (@"ACK"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(three)),Str(@ACK))*/
    XCTAssertEqualObjects(((expr_3_t *)_r).three, (@"@ACK"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(four)),Str(_ACK_))*/
    XCTAssertEqualObjects(((expr_3_t *)_r).four, (@"_ACK_"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_eq)),Bool(true))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_eq.boolValue, YES);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_ne)),Bool(false))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_ne.boolValue, NO);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_lt)),Bool(true))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_lt.boolValue, YES);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_gt)),Bool(false))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_gt.boolValue, NO);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_le)),Bool(true))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_le.boolValue, YES);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_ge)),Bool(false))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_ge.boolValue, NO);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(is_str_lt2)),Bool(true))*/
    XCTAssertEqual(((expr_3_t *)_r).is_str_lt2.boolValue, YES);
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(test_not)),Bool(true))*/
    XCTAssertEqual(((expr_3_t *)_r).test_not.boolValue, YES);
}
@end
