// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "default_endian_expr_inherited.h"

@interface default_endian_expr_inherited : XCTestCase
@property (strong) default_endian_expr_inherited_t *r;
@end

@implementation default_endian_expr_inherited

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/endian_expr.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [default_endian_expr_inherited_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_default_endian_expr_inherited {
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(0)),identifier(indicator)),List(ArrayBuffer(IntNum(73), IntNum(73))))*/
    XCTAssertEqualObjects(((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[0]).indicator, ([NSData dataWithBytes:"\x49\x49" length:2]));
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(0)),identifier(main)),identifier(insides)),identifier(some_int)),IntNum(66))*/
    XCTAssertEqual(((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[0]).main).insides).some_int.unsignedIntValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(0)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int1)),IntNum(16896))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[0]).main).insides).more).some_int1.unsignedShortValue, 16896);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(0)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int2)),IntNum(66))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[0]).main).insides).more).some_int2.unsignedShortValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(0)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_inst)),IntNum(66))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[0]).main).insides).more).some_inst.unsignedIntValue, 66);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(1)),identifier(indicator)),List(ArrayBuffer(IntNum(77), IntNum(77))))*/
    XCTAssertEqualObjects(((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[1]).indicator, ([NSData dataWithBytes:"\x4D\x4D" length:2]));
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(1)),identifier(main)),identifier(insides)),identifier(some_int)),IntNum(66))*/
    XCTAssertEqual(((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[1]).main).insides).some_int.unsignedIntValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(1)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int1)),IntNum(66))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[1]).main).insides).more).some_int1.unsignedShortValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(1)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int2)),IntNum(16896))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[1]).main).insides).more).some_int2.unsignedShortValue, 16896);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(1)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_inst)),IntNum(1107296256))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[1]).main).insides).more).some_inst.unsignedIntValue, 1107296256);
    /* simpleAssert: TestAssert(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(2)),identifier(indicator)),List(ArrayBuffer(IntNum(88), IntNum(88))))*/
    XCTAssertEqualObjects(((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[2]).indicator, ([NSData dataWithBytes:"\x58\x58" length:2]));
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(2)),identifier(main)),identifier(insides)),identifier(some_int)),IntNum(66))*/
    XCTAssertEqual(((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[2]).main).insides).some_int.unsignedIntValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(2)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int1)),IntNum(66))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[2]).main).insides).more).some_int1.unsignedShortValue, 66);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(2)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_int2)),IntNum(16896))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[2]).main).insides).more).some_int2.unsignedShortValue, 16896);
    /* simpleAssert: TestAssert(Attribute(Attribute(Attribute(Attribute(Subscript(Attribute(Name(identifier(q1w2e3)),identifier(docs)),IntNum(2)),identifier(main)),identifier(insides)),identifier(more)),identifier(some_inst)),IntNum(1107296256))*/
    XCTAssertEqual(((subsub_obj_sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((sub_obj_main_obj_doc_default_endian_expr_inherited_t *)((main_obj_doc_default_endian_expr_inherited_t *)((doc_default_endian_expr_inherited_t *)((default_endian_expr_inherited_t *)_r).docs[2]).main).insides).more).some_inst.unsignedIntValue, 1107296256);
}
@end
