// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "bits_byte_aligned.h"

@interface bits_byte_aligned : XCTestCase
@property (strong) bits_byte_aligned_t *r;
@end

@implementation bits_byte_aligned

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [bits_byte_aligned_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_bits_byte_aligned {
    XCTAssertEqual(_r.one.unsignedCharValue, 20);
    XCTAssertEqual(_r.byte_1.unsignedCharValue, 65);
    XCTAssertEqual(_r.two.unsignedCharValue, 2);
    XCTAssertEqual(_r.three.boolValue, NO);
    XCTAssertEqual(_r.byte_2.unsignedCharValue, 75);
    XCTAssertEqual(_r.four.unsignedShortValue, 2892);
    XCTAssertEqualObjects(_r.byte_3, [NSData dataWithBytes:"\xFF" length:1]);
    XCTAssertEqual(_r.full_byte.unsignedCharValue, 255);
    XCTAssertEqual(_r.byte_4.unsignedCharValue, 80);
}
@end
