// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent.h"

@interface nav_parent : XCTestCase
@property (strong) KSNavParent *r;
@end

@implementation nav_parent

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNavParent initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent {
    XCTAssertEqual(((KSHeaderObj_NavParent *)((KSNavParent *)_r).header).qty_entries.unsignedIntValue, 2);
    XCTAssertEqual(((KSHeaderObj_NavParent *)((KSNavParent *)_r).header).filename_len.unsignedIntValue, 8);
    XCTAssertEqual(((KSIndexObj_NavParent *)((KSNavParent *)_r).index).entries.count, 2);
    XCTAssertEqualObjects(((KSEntry_NavParent *)((KSIndexObj_NavParent *)((KSNavParent *)_r).index).entries[0]).filename, (@"FIRST___"));
    XCTAssertEqualObjects(((KSEntry_NavParent *)((KSIndexObj_NavParent *)((KSNavParent *)_r).index).entries[1]).filename, (@"SECOND__"));
}
@end
