// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "params_call_short.h"

@interface params_call_short : XCTestCase
@property (strong) params_call_short_t *r;
@end

@implementation params_call_short

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [params_call_short_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_params_call_short {
    XCTAssertEqualObjects(((my_str1_params_call_short_t *)((params_call_short_t *)_r).buf1).body, (@"foo|b"));
    XCTAssertEqualObjects(((my_str2_params_call_short_t *)((params_call_short_t *)_r).buf2).body, (@"ar|ba"));
    XCTAssertEqual(((my_str2_params_call_short_t *)((params_call_short_t *)_r).buf2).trailer.unsignedCharValue, 122);
}
@end
