// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_until_sized.h"

@interface repeat_until_sized : XCTestCase
@property (strong) repeat_until_sized_t *r;
@end

@implementation repeat_until_sized

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_until_process.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [repeat_until_sized_t initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_until_sized {
    XCTAssertEqual(((repeat_until_sized_t *)_r).records.count, 3);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[0]).marker.unsignedCharValue, 232);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[0]).body.unsignedIntValue, 2863311546UL);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[1]).marker.unsignedCharValue, 250);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[1]).body.unsignedIntValue, 2863315102UL);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[2]).marker.unsignedCharValue, 170);
    XCTAssertEqual(((record_repeat_until_sized_t *)((repeat_until_sized_t *)_r).records[2]).body.unsignedIntValue, 1431655765);
}
@end
