// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_negative.h"

@interface enum_negative : XCTestCase
@property (strong) enum_negative_t *r;
@end

@implementation enum_negative

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_negative.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [enum_negative_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_negative {
    XCTAssertEqualObjects(((enum_negative_t *)_r).f1, ([@"negative_one" KSENUMWithDictionary:enum_negative_t._constants]));
    XCTAssertEqualObjects(((enum_negative_t *)_r).f2, ([@"positive_one" KSENUMWithDictionary:enum_negative_t._constants]));
}
@end
