// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "repeat_n_strz_double.h"

@interface repeat_n_strz_double : XCTestCase
@property (strong) repeat_n_strz_double_t *r;
@end

@implementation repeat_n_strz_double

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_n_strz.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [repeat_n_strz_double_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_repeat_n_strz_double {
    XCTAssertEqual(((repeat_n_strz_double_t *)_r).qty.unsignedIntValue, 2);
    XCTAssertEqualObjects(((repeat_n_strz_double_t *)_r).lines1, (@[@"foo"]));
    XCTAssertEqualObjects(((repeat_n_strz_double_t *)_r).lines2, (@[@"bar"]));
}
@end
