// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_3.h"

@interface expr_3 : XCTestCase
@property (strong) expr_3_t *r;
@end

@implementation expr_3

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [expr_3_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_3 {
    XCTAssertEqual(_r.one.unsignedCharValue, 80);
    XCTAssertEqualObjects(_r.two, @"ACK");
    XCTAssertEqualObjects(_r.three, @"@ACK");
    XCTAssertEqualObjects(_r.four, @"_ACK_");
    XCTAssertEqual(_r.is_str_eq.boolValue, YES);
    XCTAssertEqual(_r.is_str_ne.boolValue, NO);
    XCTAssertEqual(_r.is_str_lt.boolValue, YES);
    XCTAssertEqual(_r.is_str_gt.boolValue, NO);
    XCTAssertEqual(_r.is_str_le.boolValue, YES);
    XCTAssertEqual(_r.is_str_ge.boolValue, NO);
    XCTAssertEqual(_r.is_str_lt2.boolValue, YES);
    XCTAssertEqual(_r.test_not.boolValue, YES);
}
@end
