// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent_false2.h"

@interface nav_parent_false2 : XCTestCase
@property (strong) KSNavParentFalse2 *r;
@end

@implementation nav_parent_false2

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSNavParentFalse2 structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent_false2 {
    XCTAssertEqual(((KSChild_NavParentFalse2 *)((KSNavParentFalse2 *)_r).parentless).foo.unsignedCharValue, 80);
}
@end
