// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "str_literals2.h"

@interface str_literals2 : XCTestCase
@property (strong) str_literals2_t *r;
@end

@implementation str_literals2

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [str_literals2_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_str_literals2 {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(dollar1)),Str($foo))*/
    XCTAssertEqualObjects(((str_literals2_t *)_r).dollar1, (@"$foo"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(dollar2)),Str(${foo}))*/
    XCTAssertEqualObjects(((str_literals2_t *)_r).dollar2, (@"${foo}"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(sl2_hash)),Str(#{foo}))*/
    XCTAssertEqualObjects(((str_literals2_t *)_r).sl2_hash, (@"#{foo}"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(at_sign)),Str(@foo))*/
    XCTAssertEqualObjects(((str_literals2_t *)_r).at_sign, (@"@foo"));
}
@end
