// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_sizeof_value_0.h"

@interface expr_sizeof_value_0 : XCTestCase
@property (strong) expr_sizeof_value_0_t *r;
@end

@implementation expr_sizeof_value_0

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [expr_sizeof_value_0_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_sizeof_value_0 {
    XCTAssertEqual(((expr_sizeof_value_0_t *)_r).self_sizeof.unsignedLongLongValue, (((1 + 4) + 2) + 2));
    XCTAssertEqual(((expr_sizeof_value_0_t *)_r).sizeof_block.unsignedLongLongValue, ((1 + 4) + 2));
    XCTAssertEqual(((expr_sizeof_value_0_t *)_r).sizeof_block_a.unsignedLongLongValue, 1);
    XCTAssertEqual(((expr_sizeof_value_0_t *)_r).sizeof_block_b.unsignedLongLongValue, 4);
    XCTAssertEqual(((expr_sizeof_value_0_t *)_r).sizeof_block_c.unsignedLongLongValue, 2);
}
@end
