// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "user_type.h"

@interface user_type : XCTestCase
@property (strong) KSUserType *r;
@end

@implementation user_type

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/repeat_until_s4.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSUserType structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_user_type {
    XCTAssertEqual(((KSHeader_UserType *)((KSUserType *)_r).one).width.unsignedIntValue, 66);
    XCTAssertEqual(((KSHeader_UserType *)((KSUserType *)_r).one).height.unsignedIntValue, 4919);
}
@end
