// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_sizeof_type_1.h"

@interface expr_sizeof_type_1 : XCTestCase
@property (strong) expr_sizeof_type_1_t *r;
@end

@implementation expr_sizeof_type_1

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [expr_sizeof_type_1_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_sizeof_type_1 {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(sizeof_block)),BinOp(BinOp(BinOp(IntNum(1),Add,IntNum(4)),Add,IntNum(2)),Add,IntNum(4)))*/
    XCTAssertEqual(((expr_sizeof_type_1_t *)_r).sizeof_block.unsignedLongLongValue, (((1 + 4) + 2) + 4));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(sizeof_subblock)),IntNum(4))*/
    XCTAssertEqual(((expr_sizeof_type_1_t *)_r).sizeof_subblock.unsignedLongLongValue, 4);
}
@end
