// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "term_strz.h"

@interface term_strz : XCTestCase
@property (strong) term_strz_t *r;
@end

@implementation term_strz

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [term_strz_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_term_strz {
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(s1)),Str(foo))*/
    XCTAssertEqualObjects(((term_strz_t *)_r).s1, (@"foo"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(s2)),Str(bar))*/
    XCTAssertEqualObjects(((term_strz_t *)_r).s2, (@"bar"));
    /* simpleAssert: TestAssert(Attribute(Name(identifier(q1w2e3)),identifier(s3)),Str(|baz@))*/
    XCTAssertEqualObjects(((term_strz_t *)_r).s3, (@"|baz@"));
}
@end
