// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "term_bytes.h"

@interface term_bytes : XCTestCase
@property (strong) KSTermBytes *r;
@end

@implementation term_bytes

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSTermBytes structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_term_bytes {
    XCTAssertEqualObjects(((KSTermBytes *)_r).s1, ([NSData dataWithBytes:"\x66\x6F\x6F" length:3]));
    XCTAssertEqualObjects(((KSTermBytes *)_r).s2, ([NSData dataWithBytes:"\x62\x61\x72" length:3]));
    XCTAssertEqualObjects(((KSTermBytes *)_r).s3, ([NSData dataWithBytes:"\x7C\x62\x61\x7A\x40" length:5]));
}
@end
