// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_0.h"

@interface expr_0 : XCTestCase
@property (strong) expr_0_t *r;
@end

@implementation expr_0

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/str_encodings.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [expr_0_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_0 {
    XCTAssertEqual(_r.must_be_f7.unsignedLongLongValue, 247);
    XCTAssertEqualObjects(_r.must_be_abc123, @"abc123");
}
@end
