// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "if_values.h"

@interface if_values : XCTestCase
@property (strong) if_values_t *r;
@end

@implementation if_values

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [if_values_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_if_values {
    XCTAssertEqual(_r.codes[0].opcode.unsignedCharValue, 80);
    XCTAssertEqual(_r.codes[0].half_opcode.unsignedLongLongValue, 40);
    XCTAssertEqual(_r.codes[1].opcode.unsignedCharValue, 65);
    XCTAssertNil(_r.codes[1].half_opcode);
    XCTAssertEqual(_r.codes[2].opcode.unsignedCharValue, 67);
    XCTAssertNil(_r.codes[2].half_opcode);
}
@end
