// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nav_parent3.h"

@interface nav_parent3 : XCTestCase
@property (strong) nav_parent3_t *r;
@end

@implementation nav_parent3

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/nav_parent2.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [nav_parent3_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nav_parent3 {
    XCTAssertEqual(((nav_parent3_t *)_r).ofs_tags.unsignedIntValue, 8);
    XCTAssertEqual(((nav_parent3_t *)_r).num_tags.unsignedIntValue, 2);
    XCTAssertEqualObjects(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[0]).name, (@"RAHC"));
    XCTAssertEqual(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[0]).ofs.unsignedIntValue, 32);
    XCTAssertEqual(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[0]).num_items.unsignedIntValue, 3);
    XCTAssertEqualObjects(((tag_char_tag_nav_parent3_t *)((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[0]).tag_content).content, (@"foo"));
    XCTAssertEqualObjects(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[1]).name, (@"RAHC"));
    XCTAssertEqual(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[1]).ofs.unsignedIntValue, 35);
    XCTAssertEqual(((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[1]).num_items.unsignedIntValue, 6);
    XCTAssertEqualObjects(((tag_char_tag_nav_parent3_t *)((tag_nav_parent3_t *)((nav_parent3_t *)_r).tags[1]).tag_content).content, (@"barbaz"));
}
@end
