// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "str_literals2.h"

@interface str_literals2 : XCTestCase
@property (strong) str_literals2_t *r;
@end

@implementation str_literals2

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [str_literals2_t initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_str_literals2 {
    XCTAssertEqualObjects(((str_literals2_t *)_r).dollar1, (@"$foo"));
    XCTAssertEqualObjects(((str_literals2_t *)_r).dollar2, (@"${foo}"));
    XCTAssertEqualObjects(((str_literals2_t *)_r).sl2_hash, (@"#{foo}"));
    XCTAssertEqualObjects(((str_literals2_t *)_r).at_sign, (@"@foo"));
}
@end
