// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "js_signed_right_shift.h"

@interface js_signed_right_shift : XCTestCase
@property (strong) js_signed_right_shift_t *r;
@end

@implementation js_signed_right_shift

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [js_signed_right_shift_t structWith:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_js_signed_right_shift {
    XCTAssertEqual(_r.should_be_40000000.unsignedLongLongValue, 1073741824);
    XCTAssertEqual(_r.should_be_a00000.unsignedLongLongValue, 10485760);
}
@end
