// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "nested_types3.h"

@interface nested_types3 : XCTestCase
@property (strong) nested_types3_t *r;
@end

@implementation nested_types3

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/fixed_struct.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [nested_types3_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_nested_types3 {
    XCTAssertEqual(((subtype_cc_subtype_a_nested_types3_t *)((nested_types3_t *)_r).a_cc).value_cc.charValue, 80);
    XCTAssertEqual(((subtype_d_subtype_c_subtype_a_nested_types3_t *)((nested_types3_t *)_r).a_c_d).value_d.charValue, 65);
    XCTAssertEqual(((subtype_b_nested_types3_t *)((nested_types3_t *)_r).b).value_b.charValue, 67);
    XCTAssertEqual(((subtype_cc_subtype_a_nested_types3_t *)((subtype_b_nested_types3_t *)((nested_types3_t *)_r).b).a_cc).value_cc.charValue, 75);
    XCTAssertEqual(((subtype_d_subtype_c_subtype_a_nested_types3_t *)((subtype_b_nested_types3_t *)((nested_types3_t *)_r).b).a_c_d).value_d.charValue, 45);
}
@end
