// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "expr_enum.h"

@interface expr_enum : XCTestCase
@property (strong) KSExprEnum *r;
@end

@implementation expr_enum

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/term_strz.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSExprEnum initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_expr_enum {
    XCTAssertEqualObjects(((KSExprEnum *)_r).const_dog, ([@"dog" KSENUMWithDictionary:KSExprEnum._animal]));
    XCTAssertEqualObjects(((KSExprEnum *)_r).derived_boom, ([@"boom" KSENUMWithDictionary:KSExprEnum._animal]));
    XCTAssertEqualObjects(((KSExprEnum *)_r).derived_dog, ([@"dog" KSENUMWithDictionary:KSExprEnum._animal]));
}
@end
