// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "enum_of_value_inst.h"

@interface enum_of_value_inst : XCTestCase
@property (strong) KSEnumOfValueInst *r;
@end

@implementation enum_of_value_inst

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/enum_0.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSEnumOfValueInst initWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_enum_of_value_inst {
    XCTAssertEqualObjects(((KSEnumOfValueInst *)_r).pet_1, ([@"cat" KSENUMWithDictionary:KSEnumOfValueInst._animal]));
    XCTAssertEqualObjects(((KSEnumOfValueInst *)_r).pet_2, ([@"chicken" KSENUMWithDictionary:KSEnumOfValueInst._animal]));
    XCTAssertEqualObjects(((KSEnumOfValueInst *)_r).pet_3, ([@"dog" KSENUMWithDictionary:KSEnumOfValueInst._animal]));
    XCTAssertEqualObjects(((KSEnumOfValueInst *)_r).pet_4, ([@"dog" KSENUMWithDictionary:KSEnumOfValueInst._animal]));
}
@end
