// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "process_coerce_bytes.h"

@interface process_coerce_bytes : XCTestCase
@property (strong) KSProcessCoerceBytes *r;
@end

@implementation process_coerce_bytes

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/process_coerce_bytes.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSProcessCoerceBytes structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_process_coerce_bytes {
    XCTAssertEqual(((KSRecord_ProcessCoerceBytes *)((KSProcessCoerceBytes *)_r).records[0]).flag.unsignedCharValue, 0);
    XCTAssertEqualObjects(((KSRecord_ProcessCoerceBytes *)((KSProcessCoerceBytes *)_r).records[0]).buf, ([NSData dataWithBytes:"\x41\x41\x41\x41" length:4]));
    XCTAssertEqual(((KSRecord_ProcessCoerceBytes *)((KSProcessCoerceBytes *)_r).records[1]).flag.unsignedCharValue, 1);
    XCTAssertEqualObjects(((KSRecord_ProcessCoerceBytes *)((KSProcessCoerceBytes *)_r).records[1]).buf, ([NSData dataWithBytes:"\x42\x42\x42\x42" length:4]));
}
@end
