// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "default_endian_expr_inherited.h"

@interface default_endian_expr_inherited : XCTestCase
@property (strong) KSDefaultEndianExprInherited *r;
@end

@implementation default_endian_expr_inherited

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/endian_expr.bin"];
    KSStream *ks = [KSStream streamWithURL:dataURL];
    self.r = [KSDefaultEndianExprInherited structWithStream:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_default_endian_expr_inherited {
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[0]).indicator, ([NSData dataWithBytes:"\x49\x49" length:2]));
    XCTAssertEqual(((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[0]).main).insides).some_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[0]).main).insides).more).some_int1.unsignedShortValue, 16896);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[0]).main).insides).more).some_int2.unsignedShortValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[0]).main).insides).more).some_inst.unsignedIntValue, 66);
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[1]).indicator, ([NSData dataWithBytes:"\x4D\x4D" length:2]));
    XCTAssertEqual(((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[1]).main).insides).some_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[1]).main).insides).more).some_int1.unsignedShortValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[1]).main).insides).more).some_int2.unsignedShortValue, 16896);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[1]).main).insides).more).some_inst.unsignedIntValue, 1107296256);
    XCTAssertEqualObjects(((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[2]).indicator, ([NSData dataWithBytes:"\x58\x58" length:2]));
    XCTAssertEqual(((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[2]).main).insides).some_int.unsignedIntValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[2]).main).insides).more).some_int1.unsignedShortValue, 66);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[2]).main).insides).more).some_int2.unsignedShortValue, 16896);
    XCTAssertEqual(((KSSubsubObj_SubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSSubObj_MainObj_Doc_DefaultEndianExprInherited *)((KSMainObj_Doc_DefaultEndianExprInherited *)((KSDoc_DefaultEndianExprInherited *)((KSDefaultEndianExprInherited *)_r).docs[2]).main).insides).more).some_inst.unsignedIntValue, 1107296256);
}
@end
