// Autogenerated from KST: please remove this line if doing any edits by hand!

#import <XCTest/XCTest.h>
#import "instance_io_user.h"

@interface instance_io_user : XCTestCase
@property (strong) instance_io_user_t *r;
@end

@implementation instance_io_user

- (void)setUp {
    [super setUp];
    NSURL *dataURL = [NSURL fileURLWithPath:@"src/instance_io.bin"];
    kstream *ks = [kstream streamWithURL:dataURL];
    self.r = [instance_io_user_t initialize:ks];
}

- (void)tearDown {
    [super tearDown];
    self.r = nil;
}

- (void)test_instance_io_user {
    XCTAssertEqual(((instance_io_user_t *)_r).qty_entries.unsignedIntValue, 3);
    XCTAssertEqualObjects(((entry_instance_io_user_t *)((instance_io_user_t *)_r).entries[0]).name, (@"the"));
    XCTAssertEqualObjects(((entry_instance_io_user_t *)((instance_io_user_t *)_r).entries[1]).name, (@"rainy"));
    XCTAssertEqualObjects(((entry_instance_io_user_t *)((instance_io_user_t *)_r).entries[2]).name, (@"day it is"));
}
@end
